{"name":"Cpp exception handling","group":"HackerRank - C++ - Debugging - Cpp exception handling - Prepare - C++ - Debugging","url":"https://www.hackerrank.com/challenges/cpp-exception-handling/problem?isFullScreen=true","interactive":false,"memoryLimit":512,"timeLimit":4000,"tests":[{"input":"0\n","output":"largest proper divisor is not defined for n=0\nreturning control flow to caller\n","id":1718429438910},{"id":1718429438935,"input":"9\n","output":"result=3\nreturning control flow to caller\n"},{"id":1718429447553,"input":"0","output":""}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"CppExceptionHandling"}},"batch":{"id":"091eb84a-3212-4b50-9773-5c39feae655c","size":1},"srcPath":"c:\\Users\\shaeakh\\OneDrive\\ドキュメント\\GitHub\\hackerRank_CPP_solution\\Cpp_exception_handling.cpp"}