{"name":"Cpp exception handling","group":"HackerRank - C++ - Debugging - Cpp exception handling - Prepare - C++ - Debugging","url":"https://www.hackerrank.com/challenges/cpp-exception-handling/problem?isFullScreen=true","interactive":false,"memoryLimit":512,"timeLimit":4000,"tests":[{"input":"0\n","output":"largest proper divisor is not defined for n=0\nreturning control flow to caller\n","id":1718080067202},{"id":1718080067269,"input":"9\n","output":"result=3\nreturning control flow to caller\n"}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"CppExceptionHandling"}},"batch":{"id":"6f031c9f-fe01-49f4-8e6e-256dee4dbe5b","size":1},"srcPath":"d:\\code\\hackerRank_CPP_solution\\Cpp_exception_handling.cpp"}